# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/RedditSummarizer

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - add_ssh_keys:
          fingerprints:
            - "2e:8a:ec:cc:3b:34:9b:7c:03:3e:35:f3:00:fc:ac:f5"
      - run:
          name: Deploy Over SSH
          command: |
            scp -r -o StrictHostKeyChecking=no ~/RedditSummarizer ubuntu@18.233.158.18:

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
#      - deploy:
#          requires:
#            - build
#          # filters:
#            # branches:
#              # only: master # only deploys master branch